image: atlassian/default-image:4

definitions:
  caches:
    npm: ~/.npm

steps:
  - step: &build
      name: Build artifact
      caches:
        - node
        - npm
      script:
        - npm ci
        - npm run build
      artifacts:
        - out/**

  - step: &deploy
      name: Deploy to S3
      script:
        - pipe: atlassian/aws-s3-deploy:0.3.8
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            S3_BUCKET: $AWS_S3_BUCKET
            LOCAL_PATH: "out"
            ACL: "private"

  - step: &cloudfront
      name: Invalidate Cloudfront
      script:
        - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            DISTRIBUTION_ID: $AWS_CLOUDFRONT_ID

pipelines:
  branches:
    stage:
      - stage:
          deployment: staging
          steps:
            - step: *build
            - step: *deploy
            - step: *cloudfront

    main:
      - stage:
          deployment: production
          steps:
            - step: *build
            - step: *deploy
            - step: *cloudfront
